### ISSUE TITLE
TypeError getMonth()

### ISSUE THREAD

**Issue by sebastian-kreis** [TBear79/headless-datepicker#7] opened 2017-12-25 18:19 UTC
I get a TypeError when calling getMonth and setting the month to january of the current or passed year. This happens in every locale except 'en';
Zero or nonZero based months make no difference. 

[runkit example](https://runkit.com/embed/elhvl03ziq0b)
```
var HeadlessDatepicker = require("headless-datepicker").HeadlessDatepicker;
var Calendar = HeadlessDatepicker.Calendar;
var calendar = new Calendar({
    locale: 'de',
    calendarMode: 'fixed',
    zeroBasedMonth: true,
});
  
console.log(calendar.getMonth({
    year: 2017,
    month: 0
}));
```

**Comment by TBear79** [comment] 2018-01-03 20:54
Hi laterne

Thanks for your comment. 

I've created the problem in the tests and will fix it asap.

**Comment by TBear79** [comment] 2018-01-03 21:47
Hi laterne

The issue is now solved. Can you confirm?

**Comment by sebastian-kreis** [comment] 2018-01-03 22:13
Hi TBear79
Confirmed, issue solved. Thanks for the fix.
Awesome package...

**Comment by TBear79** [comment] 2018-01-04 13:41
Thanks. Closing this issue then :-)

**Closed as completed by TBear79** 2018-01-04 13:41 UTC
